### ISSUE TITLE
refuses to download when the filename is too long.

### ISSUE THREAD

**Issue by jadedgnome** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#100]
I ran into a this problem of links not being downloaded numerous times because the generated filename is too long. 
Is there any way to truncate it when if the script encounters a url that has filename thats too long? as long as the full title gets posted in the description file, I don't mind not having it in the video file.

**Comment by BromTeque** [comment]
I know I'm not answering your question, but I might have some alternative solutions if you are interested.

You could try to enable [Windows long path](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later)? I haven't tried that myself, so I'm only guessing that it might fix the issue.

I believe running the scripts in WSL circumvents the issue entirely.

**Comment by jadedgnome** [comment]
> 

i'll try it.

**Comment by TheFrenchGhosty** [comment]
Use a shorter path.

No changes will be done to the filenames.
