### ISSUE TITLE
I need answers

### ISSUE THREAD

**Issue by look-at-the-sky** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#104]
> By default, yt-dlp tries to download the best available quality if you don't pass any options.
https://github.com/yt-dlp/yt-dlp#format-selection

> Download content in the best possible quality, better than every other software, period.
https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#features

Both projects aim to download content in the highest possible quality. This implies that neither yt-dlp nor these scripts should surpass the other in terms of quality. Therefore, the question naturally arises: what is the purpose of the 'format' option found in each script?

If these scripts are capable of downloading higher quality than yt-dlp alone, the --format segment should be promptly integrated as an update to yt-dlp.
Conversely, if these scripts do not achieve a superior quality compared to yt-dlp alone, it is nonsensical to retain the '--format' option (which, I must emphasize, constitutes approximately 80% of the script).
Should these scripts even result in lower quality downloads compared to yt-dlp on its own, the '--format' option should be eliminated altogether.
Am I wrong?

**Comment by TheFrenchGhosty** [comment]
yt-dlp by default downloads modern format first then legacy format.

My scripts also does that for all quality EXCEPT 360p and lower, where the legacy format looks better.

My scripts are therefore technically better, but also causes the collection to contain different formats which might be a downside for some people.

**Comment by look-at-the-sky** [comment]
> My scripts also does that for all quality EXCEPT 360p and lower, where the legacy format looks better.

Ok, then you could decrease the weight of each script by approximately 40%, enhancing overall readability too, by omitting the section pertaining to the "--format" flag up to the 360p resolution.

> My scripts are therefore technically better, but also causes the collection to contain different formats which might be a downside for some people.

I understand, but yt-dlp aims to download content in the highest possible quality.
To make that statement true, you should integrate your format configuration into yt-dlp itself. Additionally, the problem (I can't even understand what type of problem it should honestly be, and it could be easily resolved with a single option) only exists if you're not downloading a single video.

Furthermore, I'm curious as to why these scripts do not download the YouTube channel banner, especially when archiving an entire channel.
