### ISSUE TITLE
Archivist Channels.sh - yt-dlp: error: Invalid date format ""

### ISSUE THREAD

**Issue by realbaylen** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#108]
Unable to use script:
yt-dlp: error: Invalid date format ""

I am on the latest macOS

[output.log](https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/files/14324840/output.log)

**Comment by TheFrenchGhosty** [comment]
MacOS isn't supported.

**Comment by marcelbrueckner** [comment]
macOS's `date` implementation slightly differs from GNU date. Simply install GNU date via Homebrew (`brew install coreutils`) and replace all invocations of `date` in the scripts with `gdate`.

Following part of the script 

```bash
... --datebefore "$(date --date="30 days ago" +%Y%m%d)" ...
``` 

should then look like this


```bash
... --datebefore "$(gdate --date="30 days ago" +%Y%m%d)" ...
```

**Comment by realbaylen** [comment]
> macOS's `date` implementation slightly differs from GNU date. Simply install GNU date via Homebrew (`brew install coreutils`) and replace all invocations of `date` in the scripts with `gdate`.
> 
> Following part of the script
> 
> ```shell
> ... --datebefore "$(date --date="30 days ago" +%Y%m%d)" ...
> ```
> 
> should then look like this
> 
> ```shell
> ... --datebefore "$(gdate --date="30 days ago" +%Y%m%d)" ...
> ```

Thank you!! Worked perfectly.
