### ISSUE TITLE
Details.md is corrupted

### ISSUE THREAD

**Issue by stealthswor** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#109]
![Screenshot_20240318_173259](https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/assets/121595922/1e39f562-6cee-4d76-9abf-86ea534d1472)
This docs file is corrupted when I open it in Ocular, the document viewer that is installed in KDE. It's also broken in Kate and Kwrite.

**Comment by ankenyr** [comment]
Do you believe it is broken because its just a wall of text? That is what they are
https://raw.githubusercontent.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/master/scripts/Archivist%20Scripts/Archivist%20Scripts/Channels/Channels.sh
