### ISSUE TITLE
Comment format for Source `txt` files?

### ISSUE THREAD

**Issue by dessalines** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#111]
I'm wanting to remove a few items for download that are currently in my `Source -- .txt` files, but I'm realizing that I should have added comments specifying the item name for each line, since the youtube URL doesn't tell you what it is.

What is the correct format for comment lines in the `txt` files?

**Comment by TheFrenchGhosty** [comment]
It'a hashtags, I think (but I'm not sure) that the comment has to have its own line and can't be at the end of the URL

**Comment by dessalines** [comment]
Would you like me to do a PR to add that info to the readme or somewhere? Seems fairly useful.

**Comment by TheFrenchGhosty** [comment]
@dessalines I guess if you want sure, though it's yt-dlp's default
