### ISSUE TITLE
Move files to rclone mount

### ISSUE THREAD

**Issue by thibaultmol** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#23]
Hi,

I found this repo https://github.com/bardisty/ytdlrc
which has some really neat stuff going by moving it to a cloud remote storage automatically. This is great for archiving and allows it to run on a vps easily
If you could incorporate that into your scripts, that'd be amazing!

Cheers
Thibault

**Comment by TheFrenchGhosty** [comment]
This is a good idea, but it's kinda out of scope for this project. I won't implement it myself since I'm okay with how the files are handled, but feel free to do it.

**Comment by coopermor** [comment]
youtube-dl(c) provides --exec so you could invoke --exec 'mv {} /target_dest/' to move the file after downloading
