### ISSUE TITLE
3.0 Script issue on Mac:: Date Illegal Option

### ISSUE THREAD

**Issue by karmatia** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#49]
Running script results in following error:

$ ./Channels.sh 
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
[removed]

Date command on Mac Catalina 10.15.7 does not support date --date. Use -v instead.

Replacing: --datebefore "$(date --date="30 days ago" +%Y%m%d)"
With: --dateafter "$(date -v -1m +%Y%m%d)"

Corrects issue.

**Comment by TheFrenchGhosty** [comment]
I guess OSX doesn't use something compatible with the standard GNU Coreutils' date.

Nothing I can do about that.

>date -v -1m +%Y%m%d

This isn't a thing on linux.

**Comment by karmatia** [comment]
> I guess OSX doesn't use something compatible with the standard GNU Coreutils' date.
> 
> Nothing I can do about that.
> 
> > date -v -1m +%Y%m%d
> 
> This isn't a thing on linux.
> 
> Feel free to open a PR with explanations (in docs/) to make the scripts works on OSX, I won't do it.  

Would be my first PR. I will write something up once I find some time and test it with all the scripts. However, you can avoid altering the scripts.

You can add GNU Coreutils on a Mac via a package manager like brew, then update your path to refer to the GNU version ( Otherwise they brew with "g" prefixes ... eg date becomes gdate )

EG:
$ brew  install coreutils
==> Downloading https://homebrew.bintray.com/bottles/coreutils-8.32.catalina.bot
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/7a97ad96dfbe6abbb5c94
######################################################################## 100.0%
==> Pouring coreutils-8.32.catalina.bottle.2.tar.gz
==> Caveats
Commands also provided by macOS have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
==> Summary
🍺  /usr/local/Cellar/coreutils/8.32: 476 files, 12.5MB

This project goes  farther and essentially scripts
