### ISSUE TITLE
Missing parameter for the audio-only channel script

### ISSUE THREAD

**Issue by muchtea** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#50]
The script under scripts/Audio-Only Scripts/Archivist Scripts/Channels/Channels.sh
might be missing this: --merge-output-format "mkv".

Unless it's intentionally not needed/wanted for that particular script?

**Comment by TheFrenchGhosty** [comment]
It's intentional, there's not reason to mux audio to mkv.

**Comment by muchtea** [comment]
Makes sense to me. Does that mean the other audio-only scripts can have that parameter removed, cause they still have it?

**Comment by TheFrenchGhosty** [comment]
They can, I guess I just forgot to remove it... oops
