### ISSUE TITLE
Subtitle downloading could be better

### ISSUE THREAD

**Issue by Graydenn** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#51]
If the intent of this script collection is to end up with the best possible version of the video, you could add support for YouTube's other subtitle format. 

It's not very common, but here's an [example video](https://www.youtube.com/watch?v=9mR5y5DAVSg).

You can get the subtitle file (it's srv3) with youtube-dl, just use the `--write-sub --all-subs --sub-format=srv3` options.

Then, to convert them, the tool [YTSubConverter](https://github.com/arcusmaximus/YTSubConverter) supports being ran from the command line, and documentation for that can be found [here](https://github.com/arcusmaximus/YTSubConverter#command-line). They even have a `--visual` option to emulate the styling on YouTube as closely as possible.

In my head, this sounds like it would work relatively easy, but I don't do much of this kind of thing, and I'm not sure.

Thanks.

**Comment by TheFrenchGhosty** [comment]
all-subs should get everything, there's no reason to enforce a format. Are you sure the file isn't obtained without adding a specific format?

**Comment by Graydenn** [comment]
As far as I can tell, all-subs only grabs one for each language, and it's only grabbing the `.vtt` sub file, which _does_ have the color and position data. However, I just tested 4 video players, and none of them played back the file accurately.

Source: https://mad-d.rip/3WHTrwc.png
Playback in VLC: https://mad-d.rip/6WYu4NK.png
Playback in PotPlayer: https://mad-d.rip/5YQFYBj.png
Playback in MPV: https://mad-d.rip/4BWBkwH.png
Playback in MPC-BE: https://mad-d.rip/5ec45AK.png
Playback in  MPV with YTSubConverter converted ASS (--visual option on): https://mad-d.rip/Sjuz1PE.png

So, without the extra step, VLC seems to be the only player that can actually play back VTT with style on it, though the position is wrong and it seems to have wiped out the English translation bit. The other players just gave up and played it without style.

With the extra step, every player I tested displayed the subtitles exactly as they are shown on YouTube, like the last screenshot I added ("Playback in  MPV with YTSubConverter converted ASS (--visual option on)". 

So, while the data is there, it's not actually played back by the majority of players, and when it is, it isn't correctly done. Since it's there, though, it might not be as high priority to fix. However, I've not found a converter that can handle .VTT to another format-- I had to redownload it in SRV3 to get the desired look/results. Do with this what you will.

**Comment by TheFrenchGhosty** [comment]
Are you sure it's not an issue with the vtt files downloaded?

**Comment by Graydenn** [comment]
I mean, pretty sure. If you go inside the VTT subs at that line it has

```
00:02:05.533 --> 00:02:05.666 align:start position:0% line:0%
<c.colorFEFEFE><b>tayasui irai odai o​</b>​</c><c.red><b>dai morau morau kiriotoshi no jumyou de​
​​</b></c><c.colorFEFEFE><b>"A simple request, no problem, but the cost is [a shave of your lifespan]"​</b></c>
```

Which has color data as well as position data.

**Comment by TheFrenchGhosty** [comment]
From what I'm guessing it seems to be a video player issue. VTT should work.

@pukkandan Any idea?

**Comment by Graydenn** [comment]
If you can find a video player that will play VTT accurately, please let me know. The four I've tried are about all I can think of.

**Comment by pukkandan** [comment]
As you can see from the above comment, the sub file does indeed contain the color data. As for what player can actually display it correctly, I have no idea. You may want to try and use `--convert-sub` to change it to a format your player fully supports

**Comment by Graydenn** [comment]
Yeah man, I appreciate the help, but I've already tried that.

When converting from VTT to ASS, youtube-dl will wipe the style. There isn't even misread style when opened in a text editor-- it's just not there.

**Comment by TheFrenchGhosty** [comment]
@Graydenn Things will stay the same for now, in the VTT are indeed correct (and not broken), it's something the players needs to support. I can't do anything.

If the VTT are wrong, this is a yt-dlp issue, but I guess they're correct.

**Comment by Graydenn** [comment]
Alright, that's fair enough considering it's definitely more of a player
issue than the data not being there.

Thanks nonetheless.

**Comment by pukkandan** [comment]
> If the VTT are broken, this is a yt-dlp issue, but I guess they're correct. 

The vtt is correct. It is saved as-is from what YouTube provides. 

> VLC seems to be the only player that can actually play back VTT with style on it

Also, since VLC can play it, definitely not a yt-dlp issue

Maybe open an issue in mpv or write to potplayer devs. From the forum, I've heard potplayer devs are friendly in regards to fixing issues (although there may be a bit of a language barrier)

**Comment by TheFrenchGhosty** [comment]
Alright, closing then.

Thanks for your input @pukkandan
