### ISSUE TITLE
Scripts use youtube-dlc command instead of yt-dlp

### ISSUE THREAD

**Issue by Sono-Gomorrha** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#53]
All the scripts call the youtube-dlc command, but the command was change to yt-dlp recently. see here: https://github.com/yt-dlp/yt-dlp/releases/tag/2021.02.24

**Comment by TheFrenchGhosty** [comment]
Thank you!

**Comment by TheFrenchGhosty** [comment]
Done in #55
