### ISSUE TITLE
File size drop after using .mkv instead of .webm?

### ISSUE THREAD

**Issue by daankata** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#54]
A few months back I downloaded 322 videos of a channel from YouTube using version 2 of this script. The size of the whole folder with 322 videos in it was 246G. Now, a few months later, I decided, because of a different reason, to re-download all of the channel videos using the version 3 of this script. I noticed that all 322 videos are there, with the same names, with the same lengths and the same video resolutions, but the channel folder is now only 216G. This makes a whole 30G less.

I went to check where the big difference is, and noticed that some part of the downloaded videos, using the new version of this script, had a drop in file size without being shorter or longer and having the exact same video resolution as the old ones. But the previous videos had a .webm extension, and the new have a .mkv extension. I noticed that it was added in the script to merge the output format into mkv. What does this mean? Is quality affected here, or is mkv just having a better compression and is more efficient?

**Comment by TheFrenchGhosty** [comment]
No video were ever saved as webm, they were always muxed to mkv.

This seems to be an issue with the previous download.

**Comment by daankata** [comment]
Yes, I saw now that in the last configuration, using version 2, I have indeed not included 'merge-output-format' to mkv. But why is there such a size difference when the output is not merged to mkv? Some videos have even over 1G difference (one is 3.85G, other 2.85G), and the only difference seems to be the extension (one is .webm, other .mkv).

**Comment by TheFrenchGhosty** [comment]
@daankata Codecs must be different. Simple as that.
