### ISSUE TITLE
Add `--sleep-requests` to wait between each web page request

### ISSUE THREAD

**Issue by TheFrenchGhosty** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#59]
Copied from https://old.reddit.com/r/DataHoarder/comments/lx3ccm/ultimate_youtubedl_scripts_collection_now_on/gpmsvmx?context=3 by @pukkandan

>When scraping huge channels (like Tedx for example), you'll still get 429'd even with this. I recommend using `--sleep-requests` which waits b/w each web request instead of just b/w each download. A small value like 0.5 should be enough

**Comment by LSchallot** [comment]
I added embedded the command directly into the existing yt-dlp call.  Would you ever consider writing this script to allow for specific options to be passed?  For example, I do not see the need for "--sleep-requests 0.5" for every single download.

**Comment by TheFrenchGhosty** [comment]
@LSchallot These scripts are meant to be deployed and untouched, the way things are done currently is exactly how I want them to be.

**Comment by TheFrenchGhosty** [comment]
Done in #60
