### ISSUE TITLE
Reject Files with AV01 Encoding

### ISSUE THREAD

**Issue by coopermor** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#61]
Would you consider adding scripts that reject av01 encoding? People may choose to watch downloaded videos in Plex which does not support av01 encoded videos.

**Comment by TheFrenchGhosty** [comment]
No.

Jellyfin support AV01, it's all that matter to me.

I will never do anything to help Plex since it's a closed source spyware.

https://nmaggioni.xyz/2018/02/09/How-much-does-Plex-know-about-you/

Just use Jellyfin.
