### ISSUE TITLE
Path length limit

### ISSUE THREAD

**Issue by Mennaruuk** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#64]
Can't path length limit be bypassed by changing the [LongPathsEnabled](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/) registry entry?

**Comment by TheFrenchGhosty** [comment]
Yes, but it's buggy and not on every version of Windows.
