### ISSUE TITLE
What's the proper way of continous archival a channel that uploads a video every day?

### ISSUE THREAD

**Issue by TheMrRandomDude** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#68]
Hello! What's the proper way of archiving a channel that constantly posts new content?

I know there's 'Archivist Scripts' and 'Recent Scripts', but is there one script that does both?

From what I understand, 'Archivist Scripts' gets best quality, but not last 30 days.

So what's the way of Archiving everything at same time, and then archiving new content? Will  running the script  every day be ok? It skips already created files, yes?

Thanks :)

**Comment by TheFrenchGhosty** [comment]
Yes.
