### ISSUE TITLE
Apparently super easy to create Windows Powershell version

### ISSUE THREAD

**Issue by Rings4** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#69]
I took a closer look at the code for the Channel Archive script from your old powershell version and your current linux-only version, and noticed that if you just remove `2>&1 | tee output.log` from the end of the script and rename the file extension from .sh to .ps1, as long as youtube-dlp it installed via cmd using `python3 -m pip install --upgrade yt-dlp`, the script will work natively in Windows Powershell.

I've included the filename argument `--output "%(uploader)s/%(upload_date)s - %(title)s/%(title).40s [%(id)s].%(ext)s"` with the .40s so it limits the title length to 40 characters. In my experience, this ensures no files will be skipped due to long path in Windows, with the base path in D:\A\Archive Scripts\Channels. I also got rid of redundant information (you don't need the channel name in the video filenames, subfolder names AND main subfolder.)

I also got rid of the `--datebefore "$(date --date="30 days ago" +%Y%m%d)"` argument for my use case. It can be added back if anyone needs it.

I'm sure the same changes can be applied to the other scripts to make them also use youtube-dlp to fetch comments natively in windows. Feel free to make the necessary changes to your code yourself, or label this as a guide so others can do it themselves!

`yt-dlp --format "(bestvideo[vcodec^=av01][height>=4320][fps>30]/bestvideo[vcodec^=vp9.2][height>=4320][fps>30]/bestvideo[vcodec^=vp9][height>=4320][fps>30]/bestvideo[vcodec^=avc1][height>=4320][fps>30]/bestvideo[height>=4320][fps>30]/bestvideo[vcodec^=av01][height>=4320]/bestvideo[vcodec^=vp9.2][height>=4320]/bestvideo[vcodec^=vp9][height>=4320]/bestvideo[vcodec^=avc1][height>=4320]/bestvideo[height>=4320]/bestvideo[vcodec^=av01][height>=2880][fps>30]/bestvideo[vcodec^=vp9.2][height>=2880][fps>30]/bestvideo[vcodec^=vp9][height>=2880][fps>30]/bestvideo[vcodec^=avc1][height>=2880][fps>30]/bestvideo[height>=2880][fps>30]/bestvideo[vcodec^=av01][height>=2880]/bestvideo[vcodec^=vp9.2][height>=2880]/bestvideo[vcodec^=vp9][height>=2880]/bestvideo[vcodec^=avc1][height>=2880]/bestvideo[height>=2880]/bestvideo[vcodec^=av01][height>=2160][fps>30]/bestvideo[vcodec^=vp9.2][height>=2160][fps>30]/bestvideo[vcodec^=vp9][height>=2160][fps>30]/bestvideo[vcodec^=avc1][height>=2160][fps>30]/bestvideo[height>=2160][fps>30]/bestvideo[vcodec^=av01][height>=2160]/bestvideo[vcodec^=vp9.2][height>=2160]/bestvideo[vcodec^=vp9][height>=2160]/bestvideo[vcodec^=avc1][height>=2160]/bestvideo[height>=2160]/bestvideo[vcodec^=av01][height>=1440][fps>30]/bestvideo[vcodec^=vp9.2][height>=1440][fps>30]/bestvideo[vcodec^=vp9][height>=1440][fps>30]/bestvideo[vcodec^=avc1][height>=1440][fps>30]/bestvideo[height>=1440][fps>30]/bestvideo[vcodec^=av01][height>=1440]/bestvideo[vcodec^=vp9.2][height>=1440]/bestvideo[vcodec^=vp9][height>=1440]/bestvideo[vcodec^=avc1][height>=1440]/bestvideo[height>=1440]/bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec^=vp9.2][height>=1080][fps>30]/bestvideo[vcodec^=vp9][height>=1080][fps>30]/bestvideo[vcodec^=avc1][height>=1080][fps>30]/bestvideo[height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec^=vp9.2][height>=1080]/bestvideo[vcodec^=vp9][height>=1080]/bestvideo[vcodec^=avc1][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec^=vp9.2][height>=720][fps>30]/bestvideo[vcodec^=vp9][height>=720][fps>30]/bestvideo[vcodec^=avc1][height>=720][fps>30]/bestvideo[height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec^=vp9.2][height>=720]/bestvideo[vcodec^=vp9][height>=720]/bestvideo[vcodec^=avc1][height>=720]/bestvideo[height>=720]/bestvideo[vcodec^=av01][height>=480][fps>30]/bestvideo[vcodec^=vp9.2][height>=480][fps>30]/bestvideo[vcodec^=vp9][height>=480][fps>30]/bestvideo[vcodec^=avc1][height>=480][fps>30]/bestvideo[height>=480][fps>30]/bestvideo[vcodec^=av01][height>=480]/bestvideo[vcodec^=vp9.2][height>=480]/bestvideo[vcodec^=vp9][height>=480]/bestvideo[vcodec^=avc1][height>=480]/bestvideo[height>=480]/bestvideo[vcodec^=av01][height>=360][fps>30]/bestvideo[vcodec^=vp9.2][height>=360][fps>30]/bestvideo[vcodec^=vp9][height>=360][fps>30]/bestvideo[vcodec^=avc1][height>=360][fps>30]/bestvideo[height>=360][fps>30]/bestvideo[vcodec^=av01][height>=360]/bestvideo[vcodec^=vp9.2][height>=360]/bestvideo[vcodec^=vp9][height>=360]/bestvideo[vcodec^=avc1][height>=360]/bestvideo[height>=360]/bestvideo[vcodec^=avc1][height>=240][fps>30]/bestvideo[vcodec^=av01][height>=240][fps>30]/bestvideo[vcodec^=vp9.2][height>=240][fps>30]/bestvideo[vcodec^=vp9][height>=240][fps>30]/bestvideo[height>=240][fps>30]/bestvideo[vcodec^=avc1][height>=240]/bestvideo[vcodec^=av01][height>=240]/bestvideo[vcodec^=vp9.2][height>=240]/bestvideo[vcodec^=vp9][height>=240]/bestvideo[height>=240]/bestvideo[vcodec^=avc1][height>=144][fps>30]/bestvideo[vcodec^=av01][height>=144][fps>30]/bestvideo[vcodec^=vp9.2][height>=144][fps>30]/bestvideo[vcodec^=vp9][height>=144][fps>30]/bestvideo[height>=144][fps>30]/bestvideo[vcodec^=avc1][height>=144]/bestvideo[vcodec^=av01][height>=144]/bestvideo[vcodec^=vp9.2][height>=144]/bestvideo[vcodec^=vp9][height>=144]/bestvideo[height>=144]/bestvideo)+(bestaudio[acodec^=opus]/bestaudio)/best" --verbose --force-ipv4 --sleep-interval 5 --max-sleep-interval 30 --ignore-errors --no-continue --no-overwrites --download-archive archive.log --add-metadata --write-description --write-info-json --write-annotations --write-thumbnail --embed-thumbnail --all-subs --sub-format "srt" --embed-subs --get-comments --match-filter "!is_live & !live" --output "%(uploader)s/%(upload_date)s - %(title)s/%(title).40s [%(id)s].%(ext)s" --merge-output-format "mkv" --batch-file "Source - Channels.txt"`

**Comment by TheFrenchGhosty** [comment]
I know that it can work in powershell, it did before. But:

"Because Windows has a path length limit of 260 characters, and because of the work required (and the fact that the Windows version was untested when it existed)"

**Comment by Rings4** [comment]
> 
> 
> I know that it can work in powershell, it did before. But:
> 
> "Because Windows has a path length limit of 260 characters, and because of the work required (and the fact that the Windows version was untested when it existed)"

I'm aware that you've said that.
> Because Windows has a path length limit of 260 characters, and because of the work required

However, I explicitly explained that the .40 command I'm using truncates the title in the filename to only 40 characters, which ensures no videos get excluded due to long paths. The title already exists in the subfolder name, so it can be truncated in the filename without excluding any info. Re-read my quote below:

> I've included the filename argument --output "%(uploader)s/%(upload_date)s - %(title)s/%(title).40s [%(id)s].%(ext)s" with the .40s so it limits the title length to 40 characters. In my experience, this ensures no files will be skipped due to long path in Windows, with the base path in D:\A\Archive Scripts\Channels.

As well, I understand you said 
> (and the fact that the Windows version was untested when it existed)

However, I've tested it and have confirmed it works as well as your previous one that had official windows support by you. I've been running this for over 200 hours now and not a single issue: it behaves just as the old one did, with the addition of fetching comments.

Your above 2 conditions are met.
