### ISSUE TITLE
music.youtube.com Premium not choosing best format

### ISSUE THREAD

**Issue by Zuescho** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#74]
Not sure if this is even an issue, you can close this if you like because it is mostly a problem with music.youtube

So, YouTube Music offers a higher bit rate if you have the Premium subscription.
This script likes to take opus over everything, but in this case it is actually not the best format.
https://music.youtube.com/watch?v=ApTiwtGtf_w (example)
![powershell_2021-08-27_20-01-08](https://user-images.githubusercontent.com/13680959/131169866-a8b74a44-9316-4d4f-9422-03a53e3e8542.png)
Here we actually get offered a better version in .m4a

Of course, you got to insert your cookie, without it, you just get the basic formats.
![powershell_2021-08-27_20-03-17](https://user-images.githubusercontent.com/13680959/131170089-f6d029ab-9920-4be3-a8e2-7abfca5228cc.png)

The only time when you will most likely notice this, is when downloading from music.youtube

**Comment by github-account1111** [comment]
> This script likes to take opus over everything, but in this case it is actually not the best format.

Actually it might not necessarily be the best in 2nd pic either. [AAC-to-AAC is supposedly the least destructive lossy-to-lossy transcode option](https://hydrogenaud.io/index.php/topic,100067.0.html), and since YouTube requires (recommends?) uploads in AAC, the quality of 140 might be higher than 251.

**Comment by github-account1111** [comment]
>AAC is REALLY bad when lossy

How so? [It's roughly on par with Opus in general](https://listening-test.coresv.net/results.htm) and, as I said above, potentially superior to Opus when it comes to lossy-to-lossy (which is a distinct possibility on YouTube).

>Opus is chosen no matter what because it's the best lossy audio format.

Wouldn't is make more sense to choose the highest quality audio instead?

**Comment by TheFrenchGhosty** [comment]
>How so? It's roughly on par with Opus in general

Compression

>as I said above, potentially superior to Opus when it comes to lossy-to-lossy (which is a distinct possibility on YouTube).

Lossy to lossy is bad anyway, so I'd take a modern compressed format (Opus) before an old bad one (AAC)

>Wouldn't is make more sense to choose the highest quality audio instead?

Opus is the highest quality on youtube most of the time, and if not, it's quality is *good enough* for everything but music.

**Comment by github-account1111** [comment]
@TheFrenchGhosty No one is saying lossy-to-lossy is good, only that most of YouTube is already lossy-to-lossy and it's not something that can be controlled for.

>Compression

Can you actually answer the question?
Compression is a pretty broad term.
Flac compresses but obviously doesn't lose any quality so "compression" is a non-answer.

And how is AAC old or bad? Multiple tests confirm it's on par with Opus, including the one I linked above.

>Opus is the highest quality on youtube most of the time

It's not. Check link above.

>it's quality is good enough for everything but music.

Same can be said for AAC, with the added benefit of compatibility.

**Comment by TheFrenchGhosty** [comment]
>Can you actually answer the question?

AAC compress less than Opus for the same quality, as in: for the same quality AAC files are bigger than Opus.

>Multiple tests confirm it's on par with Opus, including the one I linked above.

Maybe, but Opus is more modern and I'd rather focus on modern format.

>It's not. Check link above.

**on youtube**

>Same can be said for AAC, with the added benefit of compatibility.

Sure, but Opus is compatible with most modern devices, and again, Opus compresses more.
