### ISSUE TITLE
EZ Question: Why 30 day delay in archival?

### ISSUE THREAD

**Issue by jacroe** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#76]
What's the reasoning for the 30 day delay? LIke, I know it's due to [YouTube's transcoding](https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/blob/master/docs/Scripts-Type.md#archivist-scripts) but why 30 days instead of, say, 5? Or 17?

**Comment by TheFrenchGhosty** [comment]
It sometimes take 20 days, so 30 day is a "safe" guess.
