### ISSUE TITLE
Revert #72/3b0cfaf - Not needed and causes missing metadata in some cases

### ISSUE THREAD

**Issue by coletdjnz** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#77]
#72 / 3b0cfaf introduced using `--extractor-args youtube:player_client=android` as a workaround for throttling, however this is no longer needed. By default, yt-dlp uses `--extractor-args youtube:player_client=android,web` (and yt-dlp also has n-sig transforming implemented now). 

**This should be reverted now** as it can lead to missing metadata and formats in some cases. If the webpage fails to download (e.g. 429), you will be relying on metadata from the android client only, which does not include data such as upload date.

**Comment by TheFrenchGhosty** [comment]
This is known, and I've been planning to do it for a while, I've just been busy.

**Comment by TheFrenchGhosty** [comment]
Fixed in https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/commit/95490ac015d378a7ab2c2f2b7f8fb2982af1fda1
