### ISSUE TITLE
technically not an issue, just a question regarding the most recent version/a past version of your archival script.

### ISSUE THREAD

**Issue by N72826** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#78]
so about 2 years ago, I found this wonderful repository and was instantly drawn to the quality selection aspect. I appreciate it so much, thank you kindly for taking the time to figure it all out. and I want to preface by apologizing for such a long thread, I will understand if this is intentional functionality for the script, but by the looks of it from an outsider's perspective, this seems unintentional.

now my question is about how the archival script determines the best quality. and why it is choosing a version that has perceivably worse quality. here is an example video I have been testing this out on once I noticed it was making some odd selections. It should also be know that I have been running an older version of your script since I found it, but even after updating to the latest version which seems to take into account the avc1 codec, it still refuses to grab the highest quality version of the file. I would have to manually select the format number which is 137 on this list. 

so to put it simply, the old version of the script that I have been running for the past two years that I'm about to show you grabs format 248, which is nice and works for the majority of the things I'm archiving. The newest version of your script grabs format version 399. and irrefutably, the best quality version available happens to be 137, and I'm not just going by filesize/bitrate when I say this as you will see in a moment from the imgsli. 
I was visually inspecting the two versions (248 and 137) to see how different the VP9 version is since this has been my go-to batch script for like 2 years, and I just noticed it wasn't grabbing the AVC1 version, which for the most part, they look identical and sometimes the VP9 version actually looks better in some frames at the beginning, but when it comes to high amounts of motion, the lack of bitrate can definitely be felt and this is what makes the AVC1 version preferable. so after I realized it wasn't downloading format 137, I was relieved to find out your scripts were still being updated to accommodate for AVC1 and that's when I got confused because it still wasn't grabbing it at peak quality.

[Adult Swim - Off The Air - Dreams](https://www.youtube.com/watch?v=vWiCVO3X_Ec)

**here is the imgsli so you can see for yourself.** https://imgsli.com/ODgxNzQ/1/2

**This is a list of available formats:**

```
# yt-dlp --list-formats https://www.youtube.com/watch?v=EYvnKc908Fw
[youtube] EYvnKc908Fw: Downloading webpage
[youtube] EYvnKc908Fw: Downloading android player API JSON
[info] Available formats for EYvnKc908Fw:
ID  EXT  RESOLUTION FPS |  FILESIZE    TBR PROTO | VCODEC          VBR ACODEC     ABR  ASR    MORE INFO
--- ---- ---------- --- - ---------- ----- ----- - ------------- ----- --------- ---- ------- -----------------
139 m4a  audio only     |  9.94MiB     48k https |                     mp4a.40.5  48k 22050Hz low, m4a_dash
249 webm audio only     |  11.07MiB    54k https |                     opus       54k 48000Hz low, webm_dash
250 webm audio only     |  14.24MiB    69k https |                     opus       69k 48000Hz low, webm_dash
140 m4a  audio only     |  26.37MiB   129k https |                     mp4a.40.2 129k 44100Hz medium, m4a_dash
251 webm audio only     |  27.00MiB   132k https |                     opus      132k 48000Hz medium, webm_dash
17  3gp  176x144    12  |  14.86MiB    72k https | mp4v.20.3       72k mp4a.40.2   0k 22050Hz 144p
394 mp4  256x144    24  |  12.04MiB    59k https | av01.0.00M.08   59k                        144p, mp4_dash
160 mp4  256x144    24  |  8.14MiB     39k https | avc1.4d400c     39k                        144p, mp4_dash
278 webm 256x144    24  |  14.35MiB    70k https | vp9             70k                        144p, webm_dash
395 mp4  426x240    24  |  15.57MiB    76k https | av01.0.00M.08   76k                        240p, mp4_dash
133 mp4  426x240    24  |  13.54MiB    66k https | avc1.4d4015     66k                        240p, mp4_dash
242 webm 426x240    24  |  17.86MiB    87k https | vp9             87k                        240p, webm_dash
396 mp4  640x360    24  |  28.93MiB   142k https | av01.0.01M.08  142k                        360p, mp4_dash
134 mp4  640x360    24  |  24.59MiB   120k https | avc1.4d401e    120k                        360p, mp4_dash
18  mp4  640x360    24  |  88.90MiB   436k https | avc1.42001E    436k mp4a.40.2   0k 44100Hz 360p
243 webm 640x360    24  |  31.06MiB   152k https | vp9            152k                        360p, webm_dash
397 mp4  854x480    24  |  50.61MiB   248k https | av01.0.04M.08  248k                        480p, mp4_dash
135 mp4  854x480    24  |  37.16MiB   182k https | avc1.4d401e    182k                        480p, mp4_dash
244 webm 854x480    24  |  46.92MiB   230k https | vp9            230k                        480p, webm_dash
398 mp4  1280x720   24  |  100.44MiB  493k https | av01.0.05M.08  493k                        720p, mp4_dash
136 mp4  1280x720   24  |  68.81MiB   337k https | avc1.4d401f    337k                        720p, mp4_dash
22  mp4  1280x720   24  |             466k https | avc1.64001F    466k mp4a.40.2   0k 44100Hz 720p
247 webm 1280x720   24  |  77.60MiB   381k https | vp9            381k                        720p, webm_dash
399 mp4  1920x1080  24  |  183.75MiB  902k https | av01.0.08M.08  902k                        1080p, mp4_dash
137 mp4  1920x1080  24  |  278.13MiB 1365k https | avc1.640028   1365k                        1080p, mp4_dash
248 webm 1920x1080  24  |  215.40MiB 1057k https | vp9           1057k                        1080p, webm_dash
```

**This is the old version of your script that I have been running steadily for 2 years, and imo it was grabbing higher quality formats on some other videos I tested but maybe the newer script is just more intelligent now and grabs an indistinguishable format at a lower file size:** 

`--format "(bestvideo[vcodec=av01][height>=4320][fps>30]/bestvideo[vcodec=vp9.2][height>=4320][fps>30]/bestvideo[vcodec=vp9][height>=4320][fps>30]/bestvideo[vcodec=av01][height>=4320]/bestvideo[vcodec=vp9.2][height>=4320]/bestvideo[vcodec=vp9][height>=4320]/bestvideo[height>=4320]/bestvideo[vcodec=av01][height>=2880][fps>30]/bestvideo[vcodec=vp9.2][height>=2880][fps>30]/bestvideo[vcodec=vp9][height>=2880][fps>30]/bestvideo[vcodec=av01][height>=2880]/bestvideo[vcodec=vp9.2][height>=2880]/bestvideo[vcodec=vp9][height>=2880]/bestvideo[height>=2880]/bestvideo[vcodec=av01][height>=2160][fps>30]/bestvideo[vcodec=vp9.2][height>=2160][fps>30]/bestvideo[vcodec=vp9][height>=2160][fps>30]/bestvideo[vcodec=av01][height>=2160]/bestvideo[vcodec=vp9.2][height>=2160]/bestvideo[vcodec=vp9][height>=2160]/bestvideo[height>=2160]/bestvideo[vcodec=av01][height>=1440][fps>30]/bestvideo[vcodec=vp9.2][height>=1440][fps>30]/bestvideo[vcodec=vp9][height>=1440][fps>30]/bestvideo[vcodec=av01][height>=1440]/bestvideo[vcodec=vp9.2][height>=1440]/bestvideo[vcodec=vp9][height>=1440]/bestvideo[height>=1440]/bestvideo[vcodec=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best"`

**Comment by TheFrenchGhosty** [comment]
This is an edge case. The scripts prioritize the more recent/modern format first (AV1 then VP9 then AVC), in this case, it looks like AV1 is the worst, something that is almost NEVER the case. 

Since the scripts are made to grab the best quality available as much as possible, making AVC the priority it isn't a good idea.

Sorry, but there's no way to handle edge case in a better way.
