### ISSUE TITLE
Enable --concurrent-fragments

### ISSUE THREAD

**Issue by ridgewell** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#81]
Youtube Dash formats can be slow to download as they download fragment-by-fragment. This is not throttling but a design of Dash formats.

Does it make sense to enable yt-dlp's --concurrent-fragments (-N) with 4 or 8 threads to mitigate this issue? This mitigates the slowness of single-threaded download of dash files without requiring the use of an external downloader such as aria2.

Thank you for looking into this.

**Comment by TheFrenchGhosty** [comment]
This is a good idea from a download speed perspective, but I'm a bit scared that this will cause some bugs/weirdness when merging the fragments. So I'm not sure it's "safe".

**Comment by TheFrenchGhosty** [comment]
Done in https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/commit/4e3a1bc7d6fb03ef4e8cd182139a56c2493de128
