### ISSUE TITLE
[Questions] FFmpeg --audio-quality Flag

### ISSUE THREAD

**Issue by InTheKnown** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#84]
Hello, i just started using your script lately, and i must say i'm a fan!
I have a question, while reading [yt-dlp ReadMe](https://github.com/yt-dlp/yt-dlp#post-processing-options) i found the `--audio-quality` flag, which when set to 0 it sets ffmpeg audio quality to *best*, while 10 is *worst* (Default is 5)

Now, does this setting matter in any context? In either downloading archival or listening copies from YouTube? I think it affects bitrate in some form but i'm not sure

And at what stage does this setting matter, if added to the script?

**Comment by TheFrenchGhosty** [comment]
It seems to indeed be only for transcoding.

Can you please confirm - or not - this@pukkandan

**Comment by pukkandan** [comment]
Yes, it only matters when you --extract-audio to a specific --audio-format
