### ISSUE TITLE
Add --check-formats to avoid HTTP 503 Error Edge Case

### ISSUE THREAD

**Issue by BromTeque** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#86]
I've been archiving a large amount of channels and have started to run into a obscure issue mentioned in [YT-DLP Issue #502](https://github.com/yt-dlp/yt-dlp/issues/502). It seems the only fix is to use the `--check-formats` option.

Example: `yt-dlp https://www.youtube.com/watch?v=KvDvSuUsPI8`
Only works with the `--check-formats` option.

I've done some rudimentary testing, and it seems to be working for now.
I can create a PR upon request.

**Comment by TheFrenchGhosty** [comment]
Done in https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/commit/4e3a1bc7d6fb03ef4e8cd182139a56c2493de128

**Comment by aleksl17** [comment]
Thanks! Keep up the great work!
