### ISSUE TITLE
Script seems to be running slow? 

### ISSUE THREAD

**Issue by Degura** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#91]
Hello, 

System: Windows 10 (Using Cygwin)
YouTube DLP Version: yt-dlp 2022.04.08 (the most current one)

I have been using the script a lot and it's been pretty good. But today I noticed that my speeds dropped from about 12-13 MB/s to just  <1 MB/s. There is another program called Open Video Downloader that uses yt-dlp as well and that seems to working well (though same issue, it doesn't run at the normal speed). I have posted two comparisons below

Downloading using the Watch on PC Script: 
![image](https://user-images.githubusercontent.com/68207822/167475887-4c128d92-4132-449b-a606-748953d6916b.png)
As you can see the speeds are very slow and it takes about 10 minutes to download here.

Downloading with Open Video Downloader (Yt-dlp GUI)
![image](https://user-images.githubusercontent.com/68207822/167477202-b57b9096-af5b-4945-b967-b0e9a27736d6.png)
This does not seem to have the same issue. This also uses yt-dlp. 

This also happens on the other scripts as well.

Any help as to why this is happening with the script? I would prefer to use this since it's the best quality possible. Thank you

**Comment by Degura** [comment]
It seemed to have fixed itself by reinstalling yt-dlp. Not sure if it's the same speed but it's going at the speed I would be expecting. Sorry about that.

**Comment by TheFrenchGhosty** [comment]
Fragments download slowly compared to normal videos, the GUI is fast because it's downloading a different format (that is worse quality-wise).

Blame youtube.

**Comment by Degura** [comment]
> Fragments download slowly compared to normal videos, the GUI is fast because it's downloading a different format (that is worse quality-wise).
> 
> Blame youtube.

The problem is that the entire file doesn't seem to work. 
![image](https://user-images.githubusercontent.com/68207822/167994866-ab30ee56-6b7c-4683-b7b9-2809028104c0.png)

It's not even combining the output anymore. Something is broken.

**Comment by TheFrenchGhosty** [comment]
That's a problem on your end.
