### ISSUE TITLE
Scripts For Other Sites? (I.E. Vimeo, SoundCloud etc.)

### ISSUE THREAD

**Issue by FinleyGomezAFR** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#93]
Just wanna start off by saying thank you FrenchGhosty for creating this, it has been more than helpful for me!

I just wanted to ask if there was a possibility to implement other sites as well, seeing as YT-DLP also supports a myriad of other sites.

The main sites id love to see included as well would be:

- SoundCloud (both 128kbps and 256kbps respective)
- Vimeo (Like with YouTube, just being able to save stuff in the best quality possible, seeing as lots of businesses choose to use Vimeo for websites as well as corporate / artistic uploading)

Let me know what you think and if its feasible for these sites and more to be added to create a "Masterlist" of sorts!

**Comment by TheFrenchGhosty** [comment]
The archivist scripts are usable as-is for Vimeo.

The audio-only scripts should be perfect for Soundcloud (I do have a personal script that I tihkn is different a bit, so I'll have to recheck.

**Comment by github-account1111** [comment]
> The archivist scripts are usable as-is for Vimeo.

Are they?
They will not get the best for https://vimeo.com/377541992 and many other videos on the frontpage.
Actually I think they will fail altogether.
