### ISSUE TITLE
yt-dlp unable to find a format for a video and so just gives up.

### ISSUE THREAD

**Issue by helloeverything1** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#94]
I have been archiving a large channel and almost all videos work fine, but there is some videos where whenever the script downloads almost all the comments it starts spamming

[info] Testing format 399
[info] Unable to download format 399. Skipping...
[info] Testing format 303
[info] Unable to download format 303. Skipping...
[info] Testing format 299
[info] Unable to download format 299. Skipping...
[info] Testing format 303
[info] Unable to download format 303. Skipping...
[info] Testing format 299
[info] Unable to download format 299. Skipping...
[info] Testing format 399
[info] Unable to download format 399. Skipping...
[info] Testing format 399
[info] Unable to download format 399. Skipping...
[info] Testing format 303
[info] Unable to download format 303. Skipping...
[info] Testing format 299
[info] Unable to download format 299. Skipping...
[info] Testing format 303
[info] Unable to download format 303. Skipping...

and then after a while of that it eventually gives this error message

ERROR: [youtube] g9_aYyEDMD0: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1504, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1561, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2593, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] g9_aYyEDMD0: Requested format is not available. Use --list-formats for a list of available formats

and moves onto the next video. I have updated my yt-dlp with yt-dlp -U but I was on a version not too far away from the latest and it takes hours to download all the comments on a video to test it so I don't know if that fixed it yet. Is this an issue with the script?

**Comment by ankenyr** [comment]
This script does nothing but calls yt-dlp. You should ask yt-dlp.
