### ISSUE TITLE
Clean IP Address from metadata

### ISSUE THREAD

**Issue by Hernan-2017** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#98]
So, after downloading a few videos, I noticed that in the .json file that gets generated, inside the field "formats" there's this "url" field that contains a temp link which includes your IP Address at the moment of download, example:
`"url": "https://rr1---sn-p25g5uvqvn-jvgl.googlevideo.com/videoplayback?expire=1667531352&ei=-C1kY5bhOIjWxASryZa4DQ&ip=0.0.0.0`
I replaced it with 0.0.0.0 but it should be quite easy to find, this file also gets added on the video as well so making a script to automatically change every .json file after downloading is not an option, I think removing this bit of personal info would be a good change, I'm not aware if this is the only piece of info that would be nice to remove though.

**Comment by Hernan-2017** [comment]
Searching in Discord I found this:
`--parse-metadata ' :(?P<url>)(?P<manifest_url>)(?P<formats>)'`

The only problem is that it gives an error then trying to download, so it might be an outdated way to fix this problem, but maybe it helps.

**Comment by ankenyr** [comment]
This is better addressed by yt-dlp rather than this script.

**Comment by TheFrenchGhosty** [comment]
I agree with @ankenyr this is out of scope for those scripts.
